Add ymodem_send_*()

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,16 +1,29 @@
 
 SRC_DIR=../src
+SRCS=$(SRC_DIR)/modem_xfer.c $(SRC_DIR)/ymodem.c $(SRC_DIR)/ymodem_send.c
+HDRS=$(SRC_DIR)/modem_xfer.h $(SRC_DIR)/modem_xfer_debug.h
+#RZ=/Users/takemura/workspace/github/lrzsz-0.12.20/src/lrz
+RZ=rz
+PIPE=/tmp/modem_test
 
 all: modem_test
 
-modem_test: modem_test.c $(SRC_DIR)/modem_xfer.c $(SRC_DIR)/ymodem.c $(SRC_DIR)/modem_xfer.h $(SRC_DIR)/modem_xfer_debug.h
-	cc -I$(SRC_DIR) -DDEBUG -o modem_test modem_test.c $(SRC_DIR)/modem_xfer.c $(SRC_DIR)/ymodem.c
+modem_test: modem_test.c $(SRCS) $(HDRS)
+	cc -I$(SRC_DIR) -DDEBUG -o modem_test modem_test.c $(SRCS)
 
 test:: all
 	pkill -a modem_test || true
-	./modem_test &
-	ls -l /tmp/modem_test-*
-	sz --ymodem data/foo.txt data/bar.txt data/baz.dat < /tmp/modem_test-tx > /tmp/modem_test-rx
+	pkill -a rz || true
+	for r in 654321 123456 341278 923781; do \
+          ./modem_test --random-seed $${r} & \
+          sz --ymodem data/foo.txt data/bar.txt data/baz.dat < $(PIPE)-tx > $(PIPE)-rx; \
+          make check_test_result || exit 1; \
+          $(RZ) --ymodem --overwrite < /tmp/modem_test-tx > /tmp/modem_test-rx & \
+          ./modem_test --random-seed $${r} data/foo.txt data/bar.txt data/baz.dat; \
+          make check_test_result || exit 1; \
+        done
+
+check_test_result::
 	err_count=0; \
 	for i in foo.txt bar.txt baz.dat; do \
 	    if diff $${i} data/$${i}; then \
@@ -28,7 +41,8 @@ test:: all
 	if [ $${err_count} == 0 ]; then \
 	    echo OK;\
 	else \
-	    echo "some ERROR(s) were detected. Please check the result";\
+	    echo "some ERROR(s) were detected. Please check the result"; \
+	    exit 1; \
 	fi; \
 	echo
 
